name: SwiftExample
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: Configs/Debug.xcconfig
  Release: Configs/Release.xcconfig
options:
  groupSortPosition: top

schemes:
  StoryboardUIKitAppDelegate:
    build:
      targets:
        StoryboardUIKitAppDelegate: all

  SwiftUIUIKitAppDelegate:
    build:
      targets:
        SwiftUIUIKitAppDelegate: all

targets:
  StoryboardUIKitAppDelegate:
    type: application
    platform: iOS
    sources: 
      - StoryboardUIKitAppDelegate
      - Configs
    dependencies:
      - framework: ./Frameworks/SpotifyiOS.xcframework

  SwiftUIUIKitAppDelegate:
    type: application
    platform: iOS
    sources: 
      - SwiftUIUIKitAppDelegate
      - Configs
