name: SwiftExample
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: Configs/Debug.xcconfig
  Release: Configs/Release.xcconfig
options:
  groupSortPosition: top

packages:
  OAuthSwift:
    url: https://github.com/OAuthSwift/OAuthSwift.git
    from: 2.1.0

schemes:
  StoryboardUIKitAppDelegate:
    build:
      targets:
        StoryboardUIKitAppDelegate: all

  SpotifyExample:
    build:
      targets:
        SpotifyExample: all

targets:
  StoryboardUIKitAppDelegate:
    type: application
    platform: iOS
    sources: 
      - StoryboardUIKitAppDelegate
      - Configs

  SpotifyExample:
    type: application
    platform: iOS
    sources: 
      - SpotifyExample
      - Configs
    dependencies:
      - framework: ./Frameworks/SpotifyiOS.xcframework

  SpotifyPKCE:
    type: application
    platform: iOS
    sources: 
      - SpotifyPKCE
      - Configs
    dependencies:
      - package: OAuthSwift
