name: SwiftExample
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: Configs/Debug.xcconfig
  Release: Configs/Release.xcconfig
options:
  groupSortPosition: top

schemes:
  StoryboardUIKitAppDelegate:
    build:
      targets:
        StoryboardUIKitAppDelegate: all

  SpotifyExample:
    build:
      targets:
        SpotifyExample: all

  SpotifyPKCE:
    build:
        targets:
          SpotifyPKCE: all

targets:
  StoryboardUIKitAppDelegate:
    type: application
    platform: iOS
    sources: 
      - StoryboardUIKitAppDelegate
      - Configs

  SpotifyExample:
    type: application
    platform: iOS
    sources: 
      - SpotifyExample
      - Configs
    dependencies:
      - framework: ./Frameworks/SpotifyiOS.xcframework

  SpotifyPKCE:
    type: application
    platform: iOS
    sources: 
      - SpotifyPKCE
      - Configs
